### ISSUE TITLE
Building DLL for x64 Windows

### ISSUE THREAD

**Issue by celophi** [OpenDriver2/PsyCross#8]
Hello!

I'm using this project for a game I'm porting currently, and it's working great. However, I'm stuck trying to to produce a DLL under Windows built for x64. I'm running into a naming conflict:

```
kernel32.lib(KERNEL32.dll) : error LNK2005: `EnterCriticalSection` already defined in LIBAPI.obj
```

Seems like even though this is unimplemented, this project is also using `EnterCriticalSection` from the Windows API.
It's not a big deal - I can just rename the function in my fork, but I was wondering if there was a better way to handle it.

**Comment by SoapyMan** [comment]
Sadly there no good workaround except renaming function and placing it under macro definition. Also it doesn't do any effect anyway so it's safe to remove

**Comment by celophi** [comment]
Okay, that's fine it's kind of what I expected. Thanks, I'll close this issue!
